### ISSUE TITLE
Migracja serwera

### ISSUE THREAD

**Issue by chriswieczorek** [KrzychuW/BlackMirror#12]
- [x] Apache2
- [x] PHP 7.3
- [x] MySQL
- [x] PhpMyAdmin
- [x] Supervisor

**Comment by WerVa** [comment]
przeniesiono na odroida postawionego lokalnie u Krzycha w domu
domena zmieniona na blackmirror.best

**Comment by WerVa** [comment]
serwer skonfigurowany, dostęp do phpmyadmin przekazany Krzysztofowi. 
postawiono MariaDb w najnowszej wersji. Ponieważ Mysql miał problemy przy wersji 5.7 oraz 5.6
