### ISSUE TITLE
Naprawić kalendarz / datę wyświetlaną 

### ISSUE THREAD

**Issue by WerVa** [KrzychuW/BlackMirror#19]
Po pierwszym uruchomieniu produkcji, do poprawy jest 
- [x] wyświetlana data przerobić zwrot "za 1 dzień" na "jutro"
- [x] zmienić "za 0 dni" na "- dziś" 
- [x] pokazywanie daty wstecznej

**Comment by chriswieczorek** [comment]
Poprawione
