### ISSUE TITLE
Połączenie ze skrzynkami pocztowymi za pomocą IMAP

### ISSUE THREAD

**Issue by chriswieczorek** [KrzychuW/BlackMirror#2]
- [ ] Gmail
- [ ] microsoft
- [ ] konfiguracja ręczna

**Comment by WerVa** [comment]
Z tym bym się wstrzymał. Bardziej poszedł bym w wyciągnięcie danych z FB 
tj zaproszenia do znajomych, wiadomości, powiadomienia (tylko ikony z liczbą)

**Comment by chriswieczorek** [comment]
Udało znaleźć się sposób na pobranie tych danych.
Postaram się ogarnąć to do sobotniej prezentacji - wrzucam w milestone

**Comment by chriswieczorek** [comment]
Jest pomysł jak to rozwiązać. Jeżeli będziemy rozwijać to dodam

**Comment by chriswieczorek** [comment]
Otwieram nowego taska z poprawnym opisem - maile idą do kosza
