### ISSUE TITLE
Bugfix front

### ISSUE THREAD

**Issue by WerVa** [KrzychuW/BlackMirror#20]
- [x] "pogrubić" font od liczby stopni (pogoda)
- [x] W porozumieniu z Krzychem naprawić  wyświetlana data przerobić zwrot "za 1 dzień" na "jutro" zmienić "za 0 dni" na "- dziś" 
- [x] RSS powiększyć font , wydłużyć czas, dodać animacje, delikatnie rozjaśnić

**Comment by jlorc** [comment]
Wszystko poprawione (została animacja - później zerknę), przeprojektowałem delikatnie RSS, teraz wygląda dużo lepiej :)

**Comment by chriswieczorek** [comment]
Przenoszę temat do nowego taska https://github.com/KrzychuW/BlackMirror/issues/22 a ten zamykam

**Comment by WerVa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rozkład autobusu jeżeli ktoś dojeżdża do pracy - jest Api ztmu wraz z GPS time](https://trello.com/c/mUV45fNg/12-rozk%C5%82ad-autobusu-je%C5%BCeli-kto%C5%9B-doje%C5%BCd%C5%BCa-do-pracy-jest-api-ztmu-wraz-z-gps-time)
