### ISSUE TITLE
Animacje lustro

### ISSUE THREAD

**Issue by chriswieczorek** [KrzychuW/BlackMirror#22]
Wg mnie trzeba by dodać jakieś ładne animacje aby wszystkie akcje, które dzieją się na lustrze były ładne płynne - zmiana wiadomości, pojawianie się komponentów itp

- [x] Pojawianie się komponentów powinno być wg mnie dopiero, gdy jest załadowany - w przeciwnym razie powinien być ukryty całkowicie aby nie szpecić a po załadowaniu wjazd z np takim efektem
https://animista.net/play/entrances/swing-in/swing-in-right-fwd
- [x] Tak samo wiadomości na dole powinny jakoś ładnie się nadpisywać a nie przeskakiwać
https://animista.net/play/exits/slide-out/slide-out-left
https://animista.net/play/entrances/slide-in/slide-in-right
- [x] Plus boli mnie że zmienia się wysokość wiadomości - wg mnie powinna być ustawiona jakaś stała wysokość i nawet niech będzie trochę więcej wolnej przestrzeni byle były zawsze równe

**Comment by jlorc** [comment]
Animacja i wysokości poprawiłem. Napisałem skrypt do animacji który zmniejsza wysokość do 0 przy gaszeniu aktualnej wiadomości, i przy wypalaniu nowej ustawia ją na wysokość preferowaną. Nie widać już tego przeskoku w wysokościach i podmienianiu dynamicznie contentu komponentu Vue.

**Comment by jlorc** [comment]
Zostało dodanie loadera na środku lustra do czasu aż wszystkie dane z socketów nie zostaną zebrane, po tym pokażę wszystkie komponenty naraz i zniweluję problem wskakiwania po koleji danych komponentów.

**Comment by WerVa** [comment]
Dziękujemy Panie @jlorc  :)
