### ISSUE TITLE
Przygotować makietę dla nowego panelu

### ISSUE THREAD

**Issue by WerVa** [KrzychuW/BlackMirror#26]
Trzeba przygotować nową wizualizację dla panelu admina, tak aby było lepiej pod RWD i bardziej czytelne i przejrzyste.

Myślę, że na v0.2 wystarczy makieta a na v0.3 już to zaimplementujemy

┆Issue is synchronized with this [Trello card](https://trello.com/c/dxg5gF5I) by [Unito](https://www.unito.io/learn-more)

**Comment by WerVa** [comment]
Makieta została stworzona, projekt również rozwijany jest na środowisku testowym Nowa wersja powinna już się pojawić przy następnej prezentacji.

**Comment by chriswieczorek** [comment]
Ok zamykam. Ewentualne poprawki będziemy na bieżąco poprawiać poza tym issue
