### ISSUE TITLE
Konfiguracja VPS

### ISSUE THREAD

**Issue by WerVa** [KrzychuW/BlackMirror#8]
- [x] Postawienie VPS
- [x] Instalacja PHP 7.3
- [x] Instalacja Apache 
- [x] Dodawanie Usera
- [x] Konfiguracja domeny

- [x] Uruchomienie websocket na mikrusie
- [x] Uruchomienie domeny na porcie 443 / https

**Comment by KrzychuW** [comment]
- [x] uruchomienie websocket na mikrusie
- [ ] uruchomienie domeny na porcie 443 / https

**Comment by chriswieczorek** [comment]
www - serwer21.eu
ws - srv03.mikr.us port 20369
