### ISSUE TITLE
panel home onepage

### ISSUE THREAD

**Issue by chriswieczorek** [KrzychuW/BlackMirror#9]
Chłopaki trzeba by przygotować stronkę lądującą z takim info o naszym projekcie w skrócie. Werwa by coś narysował tylko trzeba zakodować prostego htmla z linkiem do panelu.
- [x] Makieta graficzna
- [x] Zakodowanie LP

**Comment by WerVa** [comment]
HTML stworzony + grafiki i animacje. 

Trzeba by go trochę podrasować na mobiku
+ można zrobić strzałkę w dół i o autorach dodać notkę

**Comment by WerVa** [comment]
Zaktualizowano HTML pod Mobilki + dołożono scroll page - wysłane Krzychowi w ZIPIE

**Comment by WerVa** [comment]
Poprawione layout pod kątem urządzeń mobilnych
